;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 2.4, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    2.286000|            6|
;+----------------------------------------+

M48

METRIC,LZ,00.0000
T01C2.286000
%
M71
G90
T01
X03048Y09652
X68326Y12192
X68072Y-0381
X022123Y-027661
X084328Y001956
X051486Y-02728

M30
