;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 2.4, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    0.604000|           15|
;+----------------------------------------+

M48

METRIC,LZ,00.0000
T01C0.604000
%
M71
G90
T01
X558Y405
Y461
X589Y405
Y461
X61321Y431777
X79Y444
X79036Y4191
X834Y345288
Y402288
Y460288
Y517288
X863Y345288
Y402288
X864Y460288
Y517288

M30
